name: 编译内核

on:
  push:
    branches:
      - dev/*
      - stable/*
      - Suki
  workflow_dispatch:

env:
  AOSP_TOOLCHAIN_BRANCH: android16
  AOSP_CLANG_VERSION: r547379

jobs:
  build:
    name: 编译内核
    permissions: { contents: write }
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        device:
          - beryllium
          - dipper
          - equuleus
          - perseus
          - polaris
          - ursa
    steps:
      - name: 同步仓库
        uses: actions/checkout@main
        with:
          path: kernel

      - name: 替换为 SukiSU Ultra
        working-directory: kernel
        run: |
          rm -rf drivers/kernelsu KernelSU
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s nongki

    
